version = 1.1
path = '/System/Library/CoreServices/Finder.app/Contents/Resources/Finder.sdef'

classes = [
    ('application', b'capp'),
    ('item', b'cobj'),
    ('container', b'ctnr'),
    ('computer_object', b'ccmp'),
    ('disk', b'cdis'),
    ('folder', b'cfol'),
    ('desktop_object', b'cdsk'),
    ('trash_object', b'ctrs'),
    ('file', b'file'),
    ('alias_file', b'alia'),
    ('application_file', b'appf'),
    ('document_file', b'docf'),
    ('internet_location_file', b'inlf'),
    ('clipping', b'clpf'),
    ('package', b'pack'),
    ('window', b'cwin'),
    ('Finder_window', b'brow'),
    ('desktop_window', b'dktw'),
    ('information_window', b'iwnd'),
    ('preferences_window', b'pwnd'),
    ('clipping_window', b'lwnd'),
    ('process', b'prcs'),
    ('application_process', b'pcap'),
    ('desk_accessory_process', b'pcda'),
    ('preferences', b'cprf'),
    ('label', b'clbl'),
    ('icon_family', b'ifam'),
    ('icon_view_options', b'icop'),
    ('column_view_options', b'cvop'),
    ('list_view_options', b'lvop'),
    ('column', b'lvcl'),
    ('alias_list', b'alst'),
]


enums = [
    ('read_only', b'read'),
    ('read_write', b'rdwr'),
    ('write_only', b'writ'),
    ('none', b'none'),
    ('Mac_OS_format', b'dfhf'),
    ('Mac_OS_Extended_format', b'dfh+'),
    ('UFS_format', b'dfuf'),
    ('NFS_format', b'dfnf'),
    ('audio_format', b'dfau'),
    ('ProDOS_format', b'dfpr'),
    ('MSDOS_format', b'dfms'),
    ('NTFS_format', b'dfnt'),
    ('ISO_9660_format', b'df96'),
    ('High_Sierra_format', b'dfhs'),
    ('QuickTake_format', b'dfqt'),
    ('Apple_Photo_format', b'dfph'),
    ('AppleShare_format', b'dfas'),
    ('UDF_format', b'dfud'),
    ('WebDAV_format', b'dfwd'),
    ('FTP_format', b'dfft'),
    ('Packet_written_UDF_format', b'dfpu'),
    ('Xsan_format', b'dfac'),
    ('APFS_format', b'dfap'),
    ('ExFAT_format', b'dfxf'),
    ('SMB_format', b'dfsm'),
    ('unknown_format', b'df??'),
    ('General_Information_panel', b'gpnl'),
    ('Sharing_panel', b'spnl'),
    ('Memory_panel', b'mpnl'),
    ('Preview_panel', b'vpnl'),
    ('Application_panel', b'apnl'),
    ('Languages_panel', b'pklg'),
    ('Plugins_panel', b'pkpg'),
    ('Name_and_Extension_panel', b'npnl'),
    ('Comments_panel', b'cpnl'),
    ('Content_Index_panel', b'cinl'),
    ('Burning_panel', b'bpnl'),
    ('More_Info_panel', b'minl'),
    ('Simple_Header_panel', b'shnl'),
    ('General_Preferences_panel', b'pgnp'),
    ('Label_Preferences_panel', b'plbp'),
    ('Sidebar_Preferences_panel', b'psid'),
    ('Advanced_Preferences_panel', b'padv'),
    ('icon_view', b'icnv'),
    ('list_view', b'lsvw'),
    ('column_view', b'clvw'),
    ('group_view', b'grvw'),
    ('flow_view', b'flvw'),
    ('not_arranged', b'narr'),
    ('snap_to_grid', b'grda'),
    ('arranged_by_name', b'nama'),
    ('arranged_by_modification_date', b'mdta'),
    ('arranged_by_creation_date', b'cdta'),
    ('arranged_by_size', b'siza'),
    ('arranged_by_kind', b'kina'),
    ('arranged_by_label', b'laba'),
    ('right', b'lrgt'),
    ('bottom', b'lbot'),
    ('normal', b'snrm'),
    ('reversed', b'srvs'),
    ('name_column', b'elsn'),
    ('modification_date_column', b'elsm'),
    ('creation_date_column', b'elsc'),
    ('size_column', b'elss'),
    ('kind_column', b'elsk'),
    ('label_column', b'elsl'),
    ('version_column', b'elsv'),
    ('comment_column', b'elsC'),
    ('small_icon', b'smic'),
    ('large_icon', b'lgic'),
    ('mini', b'miic'),
    ('small', b'smic'),
    ('large', b'lgic'),
    ('name', b'pnam'),
    ('modification_date', b'asmo'),
    ('creation_date', b'ascd'),
    ('size', b'phys'),
    ('kind', b'kind'),
    ('label_index', b'labi'),
    ('comment', b'comt'),
    ('version', b'vers'),
]


properties = [
    ('clipboard', b'pcli'),
    ('name', b'pnam'),
    ('visible', b'pvis'),
    ('frontmost', b'pisf'),
    ('selection', b'sele'),
    ('insertion_location', b'pins'),
    ('product_version', b'ver2'),
    ('version', b'vers'),
    ('startup_disk', b'sdsk'),
    ('desktop', b'desk'),
    ('trash', b'trsh'),
    ('home', b'home'),
    ('computer_container', b'pcmp'),
    ('Finder_preferences', b'pfrp'),
    ('name', b'pnam'),
    ('displayed_name', b'dnam'),
    ('name_extension', b'nmxt'),
    ('extension_hidden', b'hidx'),
    ('index', b'pidx'),
    ('container', b'ctnr'),
    ('disk', b'cdis'),
    ('position', b'posn'),
    ('desktop_position', b'dpos'),
    ('bounds', b'pbnd'),
    ('label_index', b'labi'),
    ('locked', b'aslk'),
    ('kind', b'kind'),
    ('description', b'dscr'),
    ('comment', b'comt'),
    ('size', b'ptsz'),
    ('physical_size', b'phys'),
    ('creation_date', b'ascd'),
    ('modification_date', b'asmo'),
    ('icon', b'iimg'),
    ('URL', b'pURL'),
    ('owner', b'sown'),
    ('group', b'sgrp'),
    ('owner_privileges', b'ownr'),
    ('group_privileges', b'gppr'),
    ('everyones_privileges', b'gstp'),
    ('information_window', b'iwnd'),
    ('properties', b'pALL'),
    ('class_', b'pcls'),
    ('entire_contents', b'ects'),
    ('expandable', b'pexa'),
    ('expanded', b'pexp'),
    ('completely_expanded', b'pexc'),
    ('container_window', b'cwnd'),
    ('id', b'ID  '),
    ('capacity', b'capa'),
    ('free_space', b'frsp'),
    ('ejectable', b'isej'),
    ('local_volume', b'isrv'),
    ('startup', b'istd'),
    ('format', b'dfmt'),
    ('journaling_enabled', b'Jrnl'),
    ('ignore_privileges', b'igpr'),
    ('warns_before_emptying', b'warn'),
    ('file_type', b'asty'),
    ('creator_type', b'fcrt'),
    ('stationery', b'pspd'),
    ('product_version', b'ver2'),
    ('version', b'vers'),
    ('original_item', b'orig'),
    ('id', b'ID  '),
    ('suggested_size', b'sprt'),
    ('minimum_size', b'mprt'),
    ('preferred_size', b'appt'),
    ('accepts_high_level_events', b'isab'),
    ('has_scripting_terminology', b'hscr'),
    ('opens_in_Classic', b'Clsc'),
    ('location', b'iloc'),
    ('clipping_window', b'lwnd'),
    ('id', b'ID  '),
    ('position', b'posn'),
    ('bounds', b'pbnd'),
    ('titled', b'ptit'),
    ('name', b'pnam'),
    ('index', b'pidx'),
    ('closeable', b'hclb'),
    ('floating', b'isfl'),
    ('modal', b'pmod'),
    ('resizable', b'prsz'),
    ('zoomable', b'iszm'),
    ('zoomed', b'pzum'),
    ('visible', b'pvis'),
    ('collapsed', b'wshd'),
    ('properties', b'pALL'),
    ('target', b'fvtg'),
    ('current_view', b'pvew'),
    ('icon_view_options', b'icop'),
    ('list_view_options', b'lvop'),
    ('column_view_options', b'cvop'),
    ('toolbar_visible', b'tbvi'),
    ('statusbar_visible', b'stvi'),
    ('sidebar_width', b'sbwi'),
    ('item', b'cobj'),
    ('current_panel', b'panl'),
    ('current_panel', b'panl'),
    ('name', b'pnam'),
    ('visible', b'pvis'),
    ('frontmost', b'pisf'),
    ('file', b'file'),
    ('file_type', b'asty'),
    ('creator_type', b'fcrt'),
    ('accepts_high_level_events', b'isab'),
    ('accepts_remote_events', b'revt'),
    ('has_scripting_terminology', b'hscr'),
    ('total_partition_size', b'appt'),
    ('partition_space_used', b'pusd'),
    ('application_file', b'appf'),
    ('desk_accessory_file', b'dafi'),
    ('window', b'cwin'),
    ('icon_view_options', b'icop'),
    ('list_view_options', b'lvop'),
    ('column_view_options', b'cvop'),
    ('folders_spring_open', b'sprg'),
    ('delay_before_springing', b'dela'),
    ('desktop_shows_hard_disks', b'pdhd'),
    ('desktop_shows_external_hard_disks', b'pehd'),
    ('desktop_shows_removable_media', b'pdrm'),
    ('desktop_shows_connected_servers', b'pdsv'),
    ('new_window_target', b'pnwt'),
    ('folders_open_in_new_windows', b'ponw'),
    ('folders_open_in_new_tabs', b'pont'),
    ('new_windows_open_in_column_view', b'pocv'),
    ('all_name_extensions_showing', b'psnx'),
    ('name', b'pnam'),
    ('index', b'pidx'),
    ('color', b'colr'),
    ('large_monochrome_icon_and_mask', b'ICN#'),
    ('large_8_bit_mask', b'l8mk'),
    ('large_32_bit_icon', b'il32'),
    ('large_8_bit_icon', b'icl8'),
    ('large_4_bit_icon', b'icl4'),
    ('small_monochrome_icon_and_mask', b'ics#'),
    ('small_8_bit_mask', b'ics8'),
    ('small_32_bit_icon', b'is32'),
    ('small_8_bit_icon', b'ics8'),
    ('small_4_bit_icon', b'ics4'),
    ('arrangement', b'iarr'),
    ('icon_size', b'lvis'),
    ('shows_item_info', b'mnfo'),
    ('shows_icon_preview', b'prvw'),
    ('text_size', b'fsiz'),
    ('label_position', b'lpos'),
    ('background_picture', b'ibkg'),
    ('background_color', b'colr'),
    ('text_size', b'fsiz'),
    ('shows_icon', b'shic'),
    ('shows_icon_preview', b'prvw'),
    ('shows_preview_column', b'shpr'),
    ('discloses_preview_pane', b'dspr'),
    ('calculates_folder_sizes', b'sfsz'),
    ('shows_icon_preview', b'prvw'),
    ('icon_size', b'lvis'),
    ('text_size', b'fsiz'),
    ('sort_column', b'srtc'),
    ('uses_relative_dates', b'urdt'),
    ('index', b'pidx'),
    ('name', b'pnam'),
    ('sort_direction', b'sord'),
    ('width', b'clwd'),
    ('minimum_width', b'clwn'),
    ('maximum_width', b'clwm'),
    ('visible', b'pvis'),
]


elements = [
    ('application', b'capp'),
    ('items', b'cobj'),
    ('containers', b'ctnr'),
    ('computer_objects', b'ccmp'),
    ('disks', b'cdis'),
    ('folders', b'cfol'),
    ('desktop_objects', b'cdsk'),
    ('trash_objects', b'ctrs'),
    ('files', b'file'),
    ('alias_files', b'alia'),
    ('application_files', b'appf'),
    ('document_files', b'docf'),
    ('internet_location_files', b'inlf'),
    ('clippings', b'clpf'),
    ('packages', b'pack'),
    ('windows', b'cwin'),
    ('Finder_windows', b'brow'),
    ('desktop_windows', b'dktw'),
    ('information_windows', b'iwnd'),
    ('preferences_windows', b'pwnd'),
    ('clipping_windows', b'lwnd'),
    ('process', b'prcs'),
    ('application_process', b'pcap'),
    ('desk_accessory_process', b'pcda'),
    ('preferences', b'cprf'),
    ('labels', b'clbl'),
    ('icon_familys', b'ifam'),
    ('icon_view_options', b'icop'),
    ('column_view_options', b'cvop'),
    ('list_view_options', b'lvop'),
    ('columns', b'lvcl'),
    ('alias_lists', b'alst'),
]


commands = [
    ('open', b'aevtodoc', [('using', b'usin'), ('with_properties', b'prdt')]),
    ('print', b'aevtpdoc', [('with_properties', b'prdt')]),
    ('quit', b'aevtquit', []),
    ('activate', b'miscactv', []),
    ('close', b'coreclos', []),
    ('count', b'corecnte', [('each', b'kocl')]),
    ('data_size', b'coredsiz', [('as_', b'rtyp')]),
    ('delete', b'coredelo', []),
    ('duplicate', b'coreclon', [('to', b'insh'), ('replacing', b'alrp'), ('routing_suppressed', b'rout'), ('exact_copy', b'exct')]),
    ('exists', b'coredoex', []),
    ('make', b'corecrel', [('new', b'kocl'), ('at', b'insh'), ('to', b'to  '), ('with_properties', b'prdt')]),
    ('move', b'coremove', [('to', b'insh'), ('replacing', b'alrp'), ('positioned_at', b'mvpl'), ('routing_suppressed', b'rout')]),
    ('select', b'miscslct', []),
    ('openVirtualLocation', b'fndrovir', []),
    ('copy', b'misccopy', []),
    ('sort', b'DATASORT', [('by', b'by  ')]),
    ('clean_up', b'fndrfclu', [('by', b'by  ')]),
    ('eject', b'fndrejct', []),
    ('empty', b'fndrempt', [('security', b'sec?')]),
    ('erase', b'fndrfera', []),
    ('reveal', b'miscmvis', []),
    ('update', b'fndrfupd', [('necessity', b'nec?'), ('registering_applications', b'reg?')]),
    ('restart', b'fndrrest', []),
    ('shut_down', b'fndrshut', []),
    ('sleep', b'fndrslep', []),
]


