version = 1.1
path = 'Finder10.sdef'

classes = [
    ('application', 'capp'),
    ('item', 'cobj'),
    ('container', 'ctnr'),
    ('computer_object', 'ccmp'),
    ('disk', 'cdis'),
    ('folder', 'cfol'),
    ('desktop_object', 'cdsk'),
    ('trash_object', 'ctrs'),
    ('file', 'file'),
    ('alias_file', 'alia'),
    ('application_file', 'appf'),
    ('document_file', 'docf'),
    ('internet_location_file', 'inlf'),
    ('clipping', 'clpf'),
    ('package', 'pack'),
    ('window', 'cwin'),
    ('Finder_window', 'brow'),
    ('desktop_window', 'dktw'),
    ('information_window', 'iwnd'),
    ('preferences_window', 'pwnd'),
    ('clipping_window', 'lwnd'),
    ('process', 'prcs'),
    ('application_process', 'pcap'),
    ('desk_accessory_process', 'pcda'),
    ('preferences', 'cprf'),
    ('label', 'clbl'),
    ('icon_family', 'ifam'),
    ('icon_view_options', 'icop'),
    ('column_view_options', 'cvop'),
    ('list_view_options', 'lvop'),
    ('column', 'lvcl'),
    ('alias_list', 'alst')]

enums = [
    ('read_only', 'read'),
    ('read_write', 'rdwr'),
    ('write_only', 'writ'),
    ('none', 'none'),
    ('Mac_OS_format', 'dfhf'),
    ('Mac_OS_Extended_format', 'dfh+'),
    ('UFS_format', 'dfuf'),
    ('NFS_format', 'dfnf'),
    ('audio_format', 'dfau'),
    ('ProDOS_format', 'dfpr'),
    ('MSDOS_format', 'dfms'),
    ('NTFS_format', 'dfnt'),
    ('ISO_9660_format', 'df96'),
    ('High_Sierra_format', 'dfhs'),
    ('QuickTake_format', 'dfqt'),
    ('Apple_Photo_format', 'dfph'),
    ('AppleShare_format', 'dfas'),
    ('UDF_format', 'dfud'),
    ('WebDAV_format', 'dfwd'),
    ('FTP_format', 'dfft'),
    ('Packet_written_UDF_format', 'dfpu'),
    ('Xsan_format', 'dfac'),
    ('unknown_format', 'df??'),
    ('General_Information_panel', 'gpnl'),
    ('Sharing_panel', 'spnl'),
    ('Memory_panel', 'mpnl'),
    ('Preview_panel', 'vpnl'),
    ('Application_panel', 'apnl'),
    ('Languages_panel', 'pklg'),
    ('Plugins_panel', 'pkpg'),
    ('Name_and_Extension_panel', 'npnl'),
    ('Comments_panel', 'cpnl'),
    ('Content_Index_panel', 'cinl'),
    ('Burning_panel', 'bpnl'),
    ('More_Info_panel', 'minl'),
    ('Simple_Header_panel', 'shnl'),
    ('General_Preferences_panel', 'pgnp'),
    ('Label_Preferences_panel', 'plbp'),
    ('Sidebar_Preferences_panel', 'psid'),
    ('Advanced_Preferences_panel', 'padv'),
    ('icon_view', 'icnv'),
    ('list_view', 'lsvw'),
    ('column_view', 'clvw'),
    ('group_view', 'grvw'),
    ('flow_view', 'flvw'),
    ('not_arranged', 'narr'),
    ('snap_to_grid', 'grda'),
    ('arranged_by_name', 'nama'),
    ('arranged_by_modification_date', 'mdta'),
    ('arranged_by_creation_date', 'cdta'),
    ('arranged_by_size', 'siza'),
    ('arranged_by_kind', 'kina'),
    ('arranged_by_label', 'laba'),
    ('right', 'lrgt'),
    ('bottom', 'lbot'),
    ('normal', 'snrm'),
    ('reversed', 'srvs'),
    ('name_column', 'elsn'),
    ('modification_date_column', 'elsm'),
    ('creation_date_column', 'elsc'),
    ('size_column', 'elss'),
    ('kind_column', 'elsk'),
    ('label_column', 'elsl'),
    ('version_column', 'elsv'),
    ('comment_column', 'elsC'),
    ('small_icon', 'smic'),
    ('large_icon', 'lgic'),
    ('mini', 'miic'),
    ('small', 'smic'),
    ('large', 'lgic'),
    ('name', 'pnam'),
    ('modification_date', 'asmo'),
    ('creation_date', 'ascd'),
    ('size', 'phys'),
    ('kind', 'kind'),
    ('label_index', 'labi'),
    ('comment', 'comt'),
    ('version', 'vers')]

properties = [
    ('clipboard', 'pcli'),
    ('name', 'pnam'),
    ('visible', 'pvis'),
    ('frontmost', 'pisf'),
    ('selection', 'sele'),
    ('insertion_location', 'pins'),
    ('product_version', 'ver2'),
    ('version', 'vers'),
    ('startup_disk', 'sdsk'),
    ('desktop', 'desk'),
    ('trash', 'trsh'),
    ('home', 'home'),
    ('computer_container', 'pcmp'),
    ('Finder_preferences', 'pfrp'),
    ('name', 'pnam'),
    ('displayed_name', 'dnam'),
    ('name_extension', 'nmxt'),
    ('extension_hidden', 'hidx'),
    ('index', 'pidx'),
    ('container', 'ctnr'),
    ('disk', 'cdis'),
    ('position', 'posn'),
    ('desktop_position', 'dpos'),
    ('bounds', 'pbnd'),
    ('label_index', 'labi'),
    ('locked', 'aslk'),
    ('kind', 'kind'),
    ('description', 'dscr'),
    ('comment', 'comt'),
    ('size', 'ptsz'),
    ('physical_size', 'phys'),
    ('creation_date', 'ascd'),
    ('modification_date', 'asmo'),
    ('icon', 'iimg'),
    ('URL', 'pURL'),
    ('owner', 'sown'),
    ('group', 'sgrp'),
    ('owner_privileges', 'ownr'),
    ('group_privileges', 'gppr'),
    ('everyones_privileges', 'gstp'),
    ('information_window', 'iwnd'),
    ('properties', 'pALL'),
    ('class_', 'pcls'),
    ('entire_contents', 'ects'),
    ('expandable', 'pexa'),
    ('expanded', 'pexp'),
    ('completely_expanded', 'pexc'),
    ('container_window', 'cwnd'),
    ('id', 'ID  '),
    ('capacity', 'capa'),
    ('free_space', 'frsp'),
    ('ejectable', 'isej'),
    ('local_volume', 'isrv'),
    ('startup', 'istd'),
    ('format', 'dfmt'),
    ('journaling_enabled', 'Jrnl'),
    ('ignore_privileges', 'igpr'),
    ('warns_before_emptying', 'warn'),
    ('file_type', 'asty'),
    ('creator_type', 'fcrt'),
    ('stationery', 'pspd'),
    ('product_version', 'ver2'),
    ('version', 'vers'),
    ('original_item', 'orig'),
    ('id', 'ID  '),
    ('suggested_size', 'sprt'),
    ('minimum_size', 'mprt'),
    ('preferred_size', 'appt'),
    ('accepts_high_level_events', 'isab'),
    ('has_scripting_terminology', 'hscr'),
    ('opens_in_Classic', 'Clsc'),
    ('location', 'iloc'),
    ('clipping_window', 'lwnd'),
    ('id', 'ID  '),
    ('position', 'posn'),
    ('bounds', 'pbnd'),
    ('titled', 'ptit'),
    ('name', 'pnam'),
    ('index', 'pidx'),
    ('closeable', 'hclb'),
    ('floating', 'isfl'),
    ('modal', 'pmod'),
    ('resizable', 'prsz'),
    ('zoomable', 'iszm'),
    ('zoomed', 'pzum'),
    ('visible', 'pvis'),
    ('collapsed', 'wshd'),
    ('properties', 'pALL'),
    ('target', 'fvtg'),
    ('current_view', 'pvew'),
    ('icon_view_options', 'icop'),
    ('list_view_options', 'lvop'),
    ('column_view_options', 'cvop'),
    ('toolbar_visible', 'tbvi'),
    ('statusbar_visible', 'stvi'),
    ('sidebar_width', 'sbwi'),
    ('item', 'cobj'),
    ('current_panel', 'panl'),
    ('current_panel', 'panl'),
    ('name', 'pnam'),
    ('visible', 'pvis'),
    ('frontmost', 'pisf'),
    ('file', 'file'),
    ('file_type', 'asty'),
    ('creator_type', 'fcrt'),
    ('accepts_high_level_events', 'isab'),
    ('accepts_remote_events', 'revt'),
    ('has_scripting_terminology', 'hscr'),
    ('total_partition_size', 'appt'),
    ('partition_space_used', 'pusd'),
    ('application_file', 'appf'),
    ('desk_accessory_file', 'dafi'),
    ('window', 'cwin'),
    ('icon_view_options', 'icop'),
    ('list_view_options', 'lvop'),
    ('column_view_options', 'cvop'),
    ('folders_spring_open', 'sprg'),
    ('delay_before_springing', 'dela'),
    ('desktop_shows_hard_disks', 'pdhd'),
    ('desktop_shows_external_hard_disks', 'pehd'),
    ('desktop_shows_removable_media', 'pdrm'),
    ('desktop_shows_connected_servers', 'pdsv'),
    ('new_window_target', 'pnwt'),
    ('folders_open_in_new_windows', 'ponw'),
    ('folders_open_in_new_tabs', 'pont'),
    ('new_windows_open_in_column_view', 'pocv'),
    ('all_name_extensions_showing', 'psnx'),
    ('name', 'pnam'),
    ('index', 'pidx'),
    ('color', 'colr'),
    ('large_monochrome_icon_and_mask', 'ICN#'),
    ('large_8_bit_mask', 'l8mk'),
    ('large_32_bit_icon', 'il32'),
    ('large_8_bit_icon', 'icl8'),
    ('large_4_bit_icon', 'icl4'),
    ('small_monochrome_icon_and_mask', 'ics#'),
    ('small_8_bit_mask', 'ics8'),
    ('small_32_bit_icon', 'is32'),
    ('small_8_bit_icon', 'ics8'),
    ('small_4_bit_icon', 'ics4'),
    ('arrangement', 'iarr'),
    ('icon_size', 'lvis'),
    ('shows_item_info', 'mnfo'),
    ('shows_icon_preview', 'prvw'),
    ('text_size', 'fsiz'),
    ('label_position', 'lpos'),
    ('background_picture', 'ibkg'),
    ('background_color', 'colr'),
    ('text_size', 'fsiz'),
    ('shows_icon', 'shic'),
    ('shows_icon_preview', 'prvw'),
    ('shows_preview_column', 'shpr'),
    ('discloses_preview_pane', 'dspr'),
    ('calculates_folder_sizes', 'sfsz'),
    ('shows_icon_preview', 'prvw'),
    ('icon_size', 'lvis'),
    ('text_size', 'fsiz'),
    ('sort_column', 'srtc'),
    ('uses_relative_dates', 'urdt'),
    ('index', 'pidx'),
    ('name', 'pnam'),
    ('sort_direction', 'sord'),
    ('width', 'clwd'),
    ('minimum_width', 'clwn'),
    ('maximum_width', 'clwm'),
    ('visible', 'pvis')]

elements = [
    ('application', 'capp'),
    ('items', 'cobj'),
    ('containers', 'ctnr'),
    ('computer_objects', 'ccmp'),
    ('disks', 'cdis'),
    ('folders', 'cfol'),
    ('desktop_objects', 'cdsk'),
    ('trash_objects', 'ctrs'),
    ('files', 'file'),
    ('alias_files', 'alia'),
    ('application_files', 'appf'),
    ('document_files', 'docf'),
    ('internet_location_files', 'inlf'),
    ('clippings', 'clpf'),
    ('packages', 'pack'),
    ('windows', 'cwin'),
    ('Finder_windows', 'brow'),
    ('desktop_windows', 'dktw'),
    ('information_windows', 'iwnd'),
    ('preferences_windows', 'pwnd'),
    ('clipping_windows', 'lwnd'),
    ('process', 'prcs'),
    ('application_process', 'pcap'),
    ('desk_accessory_process', 'pcda'),
    ('preferences', 'cprf'),
    ('labels', 'clbl'),
    ('icon_familys', 'ifam'),
    ('icon_view_options', 'icop'),
    ('column_view_options', 'cvop'),
    ('list_view_options', 'lvop'),
    ('columns', 'lvcl'),
    ('alias_lists', 'alst')]

commands = [
    ('open', 'aevtodoc', [
            ('using', 'usin'),
            ('with_properties', 'prdt')]),
    ('print_', 'aevtpdoc', [('with_properties', 'prdt')]),
    ('quit', 'aevtquit', []),
    ('activate', 'miscactv', []),
    ('close', 'coreclos', []),
    ('count', 'corecnte', [('each', 'kocl')]),
    ('data_size', 'coredsiz', [('as_', 'rtyp')]),
    ('delete', 'coredelo', []),
    (       'duplicate',
            'coreclon',
            [       ('to', 'insh'),
                    ('replacing', 'alrp'),
                    ('routing_suppressed', 'rout'),
                    ('exact_copy', 'exct')]),
    ('exists', 'coredoex', []),
    (       'make',
            'corecrel',
            [       ('new', 'kocl'),
                    ('at', 'insh'),
                    ('to', 'to  '),
                    ('with_properties', 'prdt')]),
    (       'move',
            'coremove',
            [       ('to', 'insh'),
                    ('replacing', 'alrp'),
                    ('positioned_at', 'mvpl'),
                    ('routing_suppressed', 'rout')]),
    ('select', 'miscslct', []),
    ('copy', 'misccopy', []),
    ('sort', 'DATASORT', [('by', 'by  ')]),
    ('clean_up', 'fndrfclu', [('by', 'by  ')]),
    ('eject', 'fndrejct', []),
    ('empty', 'fndrempt', [('security', 'sec?')]),
    ('erase', 'fndrfera', []),
    ('reveal', 'miscmvis', []),
    ('update', 'fndrfupd', [
            ('necessity', 'nec?'),
            ('registering_applications', 'reg?')]),
    ('restart', 'fndrrest', []),
    ('shut_down', 'fndrshut', []),
    ('sleep', 'fndrslep', [])]

